version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mini-crm-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mini-crm
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mini-crm-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mini-crm --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mini-crm-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/mini-crm
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mini-crm-network
    command: npm run dev

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  mini-crm-network:
    driver: bridge