import { Permission } from './permissions';

export enum RoleName {
  SUPER_ADMIN = 'SuperAdmin',
  ADMIN = 'Admin',
  MANAGER = 'Manager',
  AGENT = 'Agent',
  AUDITOR = 'Auditor',
}

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  [RoleName.SUPER_ADMIN]: [
    // All permissions
    Permission.LEAD_CREATE,
    Permission.LEAD_VIEW_ALL,
    Permission.LEAD_EDIT_ALL,
    Permission.LEAD_DELETE_ALL,
    Permission.LEAD_ASSIGN,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.TASK_CREATE,
    Permission.TASK_VIEW,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.USER_INVITE,
    Permission.USER_VIEW,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.ROLE_MANAGE,
    Permission.PERMISSION_VIEW,
    Permission.NOTE_CREATE,
    Permission.NOTE_VIEW,
    Permission.NOTE_UPDATE,
    Permission.NOTE_DELETE,
    Permission.FILE_UPLOAD,
    Permission.FILE_VIEW,
    Permission.FILE_DOWNLOAD,
    Permission.FILE_DELETE,
    Permission.ORG_MANAGE,
    Permission.ORG_VIEW,
    Permission.AUDIT_VIEW,
    Permission.ANALYTICS_VIEW,
  ],

  [RoleName.ADMIN]: [
    // All except org.manage
    Permission.LEAD_CREATE,
    Permission.LEAD_VIEW_ALL,
    Permission.LEAD_EDIT_ALL,
    Permission.LEAD_DELETE_ALL,
    Permission.LEAD_ASSIGN,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.TASK_CREATE,
    Permission.TASK_VIEW,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.USER_INVITE,
    Permission.USER_VIEW,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.ROLE_MANAGE,
    Permission.PERMISSION_VIEW,
    Permission.NOTE_CREATE,
    Permission.NOTE_VIEW,
    Permission.NOTE_UPDATE,
    Permission.NOTE_DELETE,
    Permission.FILE_UPLOAD,
    Permission.FILE_VIEW,
    Permission.FILE_DOWNLOAD,
    Permission.FILE_DELETE,
    Permission.ORG_VIEW,
    Permission.AUDIT_VIEW,
    Permission.ANALYTICS_VIEW,
  ],

  [RoleName.MANAGER]: [
    // View/update leads & tasks for team, create projects, assign tasks/leads
    Permission.LEAD_CREATE,
    Permission.LEAD_VIEW_ALL,
    Permission.LEAD_EDIT_ALL,
    Permission.LEAD_ASSIGN,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_VIEW,
    Permission.PROJECT_UPDATE,
    Permission.TASK_CREATE,
    Permission.TASK_VIEW,
    Permission.TASK_UPDATE,
    Permission.USER_VIEW,
    Permission.PERMISSION_VIEW,
    Permission.NOTE_CREATE,
    Permission.NOTE_VIEW,
    Permission.FILE_UPLOAD,
    Permission.FILE_VIEW,
    Permission.FILE_DOWNLOAD,
    Permission.ORG_VIEW,
    Permission.ANALYTICS_VIEW,
  ],

  [RoleName.AGENT]: [
    // CRUD only for records they own/are assigned
    Permission.LEAD_CREATE,
    Permission.LEAD_VIEW_OWN,
    Permission.LEAD_EDIT_OWN,
    Permission.PROJECT_VIEW,
    Permission.TASK_CREATE,
    Permission.TASK_VIEW,
    Permission.TASK_UPDATE,
    Permission.NOTE_CREATE,
    Permission.NOTE_VIEW,
    Permission.FILE_UPLOAD,
    Permission.FILE_VIEW,
    Permission.FILE_DOWNLOAD,
  ],

  [RoleName.AUDITOR]: [
    // Read-only on org data + audit logs
    Permission.LEAD_VIEW_ALL,
    Permission.PROJECT_VIEW,
    Permission.TASK_VIEW,
    Permission.USER_VIEW,
    Permission.PERMISSION_VIEW,
    Permission.NOTE_VIEW,
    Permission.FILE_VIEW,
    Permission.FILE_DOWNLOAD,
    Permission.ORG_VIEW,
    Permission.AUDIT_VIEW,
    Permission.ANALYTICS_VIEW,
  ],
};

export const ROLE_DESCRIPTIONS: Record<RoleName, string> = {
  [RoleName.SUPER_ADMIN]: 'Full access to all organization resources and settings',
  [RoleName.ADMIN]: 'Full access except organization management',
  [RoleName.MANAGER]: 'Manage team leads, projects, and tasks',
  [RoleName.AGENT]: 'Access to own assigned leads and tasks',
  [RoleName.AUDITOR]: 'Read-only access to organization data and audit logs',
};